### ISSUE TITLE
Reference links are broken across your documentation site

### ISSUE THREAD

**Issue by cconcannon** [webscraperio/web-scraper-documentation#8]
Everywhere that you reference the path of a .md file as a link, the rendered <a> element in .html does not resolve

e.g. `[text-selector]: Selectors/Text%20selector.md` in your .md file creates a link to https://www.webscraper.io/documentation/selectorstext-selector which doesn't exist

This is true for reference links on https://www.webscraper.io/documentation/selectors and https://www.webscraper.io/documentation/scraping-a-site and possibly more of your docs pages

**Comment by martinsbalodis** [comment]
It was a problem in the markdown rendering library. Now it is fixed. 

Big thanks! If you need any help with web scraping or maybe some free web scraper cloud credits, send us a message to the info email and just mention this.
